title: Personal Website
description: Welcome to my website
author: Zhiwei Lin
avatar: /logo123.png
email: zhiweilin27@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-target-blank
paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo123.png
social:
  name: Zhiwei Lin
  links:
    - https://github.com/zhiweilin27
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
location: NYC, U.S.A
saying: “ Work Study Relax”
subscribe: false
lang: en
